### ISSUE TITLE
Assert and refute with a negation

### ISSUE THREAD

**Issue by herwinw** [rubocop/minitest-style-guide#24]
Imagine the following statement
```ruby
assert(!expr)
```
I think this should be rewritten to `refute(expr)`. For symmetry, `refute(!expr)` should be rewritten to `assert(expr)`, although I don't expect that to happen very often. And of course, the optional message should be handled as well.

We see a few more specific examples of this in the style guide. The first example of it is `assert(!actual.nil?)`. This could (I'm not saying should) be deduced by an elimination process, where you first apply the elimination of the negated assert (resulting in `refute(actual.nil?)`), then apply the rule to use `assert_nil`. This would also provide a solution for multiple negations (e.g. `assert(!!!!!expr)` can be reduced to `refute(expr)` by applying the elimination rule 5 times).

The  `rubocop-minitest` gem is pretty inconsistent regarding this subject, some rules include a single negation, some don't. Providing a higher level construct to eliminate these negations would result in a global fix (thus providing consistency), while keeping the cops themselves as simple as possible.

**Comment by bbatsov** [comment]
It seems to me that if the point is to provide some generic handling of stacked `!` operators this should be handled by RuboCop itself, not `rubocop-minitest`. 

I agree with the general point about negation examples, though. Those can be improved and unified.

**Comment by koic** [comment]
I will close this issue because it is already defined as some `refute` rule and there is also implemented cops.
