### ISSUE TITLE
Recommend passing a failure_message when calling `assert` with a single argument

### ISSUE THREAD

**Issue by gareth** [rubocop/minitest-style-guide#41]
Developers should be encouraged to supply a failure message when making single assertions.

In these cases, the code might be readable:

```
assert page.has_content?("Widget added to cart")
```

…but the test failure message doesn't give any info other than making developers go back to the code to see the error:

> Expected false to be truthy.

I believe improving the test output is a net positive, both in situations where developer have easy access to the code (e.g. while performing TDD) and in situations where the test output is the main artifact (e.g. in continuous integration environments). But I realise that there might be other opinions, for example that adding "Expected widget to be added to card" is too much overhead for developers.

I think the ideal case is that assert helpers are more intelligent and can generate more useful messages automatically. The only way I can see to achieve that is for people to write custom `assert_*` helpers, but eventually those will end up in an `assert` call which again should have a failure message.

So I think the style guide should recommend always passing a failure message, especially to bare `assert`.

If this is a good idea, then this could also be included as a Rubocop cop. I only see one other cop that focuses on `assert` calls, `Minitest/AssertWithExpectedArgument`, which is focused on calls with *more* than one argument, and so doesn't lead to any ambiguous situations with this proposal.

Thoughts?

**Comment by koic** [comment]
I understand that there may be cases where it is better to write a failure message. But, forcing a failure message to be always written may be stressful for developers. As far as I know, there are many cases where developer can understand without a failure message and I think that failure message tend to be used when it is difficult to understand.
For example, even in the implementation of Minitest itself, there are few cases where a failure message is written.
In the olden days, when JUnit came out, failure message argument was an option for assertion method signatures, so I think it's best to respect user choices.
