### ISSUE TITLE
Add warning about inheriting from other tests

### ISSUE THREAD

**Issue by andyw8** [rubocop/minitest-style-guide#45]
As illustrated in https://github.com/ignacio-chiazzo/ruby-minitest-analyzer

> Minitest uses Ruby classes, if a Minitest class inherits from another class, it will also inherit its methods causing Minitest to run the parent's tests twice. In some cases, we want them to run them twice, but most of the time, we don't.

(cc @ignacio-chiazzo)

**Comment by ignacio-chiazzo** [comment]
I opened a PR for this https://github.com/rubocop/minitest-style-guide/pull/46. Thanks for bringing this up, Andy.
